### PR TITLE
moan

### PR DESCRIPTION
**Pull request by Qiryth**
Mmm uungh

### CODE REVIEW

**Comment by Qiryth** [comment]
moan

**Comment by dorianzgraggen** [comment]
Thank you for your pull request. 💞 Very good contribution! I'm a little bit unsure about whether its a good idea for the image to be always on top, as you cannot see the dogs face anymore on small devices. Is this intended? Maybe I'm not seeing the full picture here, can you elaborate a liitle bit further?

**Comment by Qiryth** [comment]
That is a legitimate concern. I once again was to hasty with my assumption that smaller devices do not exist. I will offer a very clean solution instead: What if you could click the gremlin and it would spin down to the bottom into a relative position? Would that be an acceptable fix for the current unacceptable state of this pull request?

**Comment by dorianzgraggen** [comment]
That's a very clever solution, I like it a lot!

At a later point we could perhaps even add a moan sound when tapping it, since in real life, gremlins also produce a sound when you tap them. (But I think that'd be something for a separate pull request.)

**Comment by Qiryth** [comment]
I was not able to animate a transition from fixed to absolute but I have instead implemented a very nice moaning sound whilst the gremlin is leaving the screen on click!
Can't wait to see it in production!

**Comment by dorianzgraggen** [comment]
LGTM!

**Comment by Qiryth** [comment]
I'm looking forward to collaborate again!

**Pull request merged**
